DROP TABLE IF EXISTS COACH_RATING;
DROP TABLE IF EXISTS ATHLETE_RATING;
DROP TABLE IF EXISTS PUBLICATION;
DROP TABLE IF EXISTS COACH_RESULT;
DROP TABLE IF EXISTS ATHLETE_RESULT;
DROP TABLE IF EXISTS COACH;
DROP TABLE IF EXISTS ATHLETE;
DROP TABLE IF EXISTS STANDARDS;
DROP TABLE IF EXISTS EXERCISE;

CREATE TABLE IF NOT EXISTS EXERCISE
(
    NAZV VARCHAR(100) PRIMARY KEY,
    TECHNIQE VARCHAR,
    WORLD_RECORD_MEN VARCHAR,
    WORLD_RECORD_WOMEN VARCHAR
);

CREATE TABLE IF NOT EXISTS STANDARDS
(
    EXERCISE_NAME VARCHAR(100),
    STRENGTH_LEVEL VARCHAR,
    WEIGHT_KG FLOAT,
    REPS_COUNT INT,
    GENDER VARCHAR(10),
    BODYWEIGHT_RATIO FLOAT,
    FOREIGN KEY(EXERCISE_NAME) REFERENCES EXERCISE(NAZV) ON UPDATE CASCADE
    PRIMARY KEY (EXERCISE_NAME, STRENGTH_LEVEL,GENDER)
);


CREATE TABLE IF NOT EXISTS ATHLETE
(
    USERNAME VARCHAR(150) PRIMARY KEY,
    PASSWD VARCHAR (200),
    FIO VARCHAR (200),
    GENDER VARCHAR(10),
    BODYWEIGHT FLOAT,
    HEIGHT FLOAT,
    AGE INT,
    SOCIAL_MEDIA VARCHAR
    ROL INT DEFAULT 1  
);

CREATE TABLE IF NOT EXISTS COACH
(
    USERNAME VARCHAR(150) PRIMARY KEY,
    PASSWD VARCHAR (200),
    FIO VARCHAR (200),
    GENDER VARCHAR(10),
    BODYWEIGHT FLOAT,
    HEIGHT FLOAT,
    AGE INT,
    SOCIAL_MEDIA VARCHAR,
    ACHIEVEMENTS VARCHAR
    ROL INT DEFAULT 2
);

CREATE TABLE IF NOT EXISTS ATHLETE_RESULT
(
    USERNAME VARCHAR(150),
    EXERCISE_NAME VARCHAR(100),
    EXECUTION_DATE TIMESTAMP,
    WEIGHT_KG FLOAT,
    REPS_COUNT INT,
    ONE_RPM FLOAT,
    FOREIGN KEY (USERNAME) REFERENCES ATHLETE(USERNAME) ON UPDATE CASCADE,
    FOREIGN KEY (EXERCISE_NAME) REFERENCES EXERCISE(NAZV) ON UPDATE CASCADE,
    PRIMARY KEY (USERNAME, EXERCISE_NAME, EXECUTION_DATE)
);

CREATE TABLE IF NOT EXISTS COACH_RESULT
(
    USERNAME VARCHAR(150),
    EXERCISE_NAME VARCHAR(100),
    EXECUTION_DATE TIMESTAMP,
    WEIGHT_KG FLOAT,
    REPS_COUNT INT,
    ONE_RPM FLOAT,
    FOREIGN KEY (USERNAME) REFERENCES COACH(USERNAME) ON UPDATE CASCADE,
    FOREIGN KEY (EXERCISE_NAME) REFERENCES EXERCISE(NAZV) ON UPDATE CASCADE,
    PRIMARY KEY (USERNAME, EXERCISE_NAME, EXECUTION_DATE)
);

CREATE TABLE IF NOT EXISTS PUBLICATION
(
    AUTHOR_USERNAME VARCHAR(150),
    PUBLICATION_DATETIME TIMESTAMP,
    TEXT VARCHAR,
    FOREIGN KEY (AUTHOR_USERNAME) REFERENCES COACH(USERNAME) ON UPDATE CASCADE,
    PRIMARY KEY (AUTHOR_USERNAME, PUBLICATION_DATETIME)
);

CREATE TABLE IF NOT EXISTS ATHLETE_RATING
(
    VIEWER_USERNAME VARCHAR(150),
    AUTHOR_USERNAME VARCHAR(150),
    PUBLICATION_DATETIME TIMESTAMP,
    STARS INT,
    COMMENT VARCHAR,
    FOREIGN KEY (VIEWER_USERNAME) REFERENCES ATHLETE(USERNAME) ON UPDATE CASCADE,
    FOREIGN KEY (AUTHOR_USERNAME, PUBLICATION_DATETIME) REFERENCES PUBLICATION(AUTHOR_USERNAME, PUBLICATION_DATETIME) ON UPDATE CASCADE,
    PRIMARY KEY(VIEWER_USERNAME, AUTHOR_USERNAME,PUBLICATION_DATETIME)
);

CREATE TABLE IF NOT EXISTS COACH_RATING
(
    VIEWER_USERNAME VARCHAR(150),
    AUTHOR_USERNAME VARCHAR(150),
    PUBLICATION_DATETIME TIMESTAMP,
    STARS INT,
    COMMENT VARCHAR,
    FOREIGN KEY (VIEWER_USERNAME) REFERENCES COACH(USERNAME) ON UPDATE CASCADE,
    FOREIGN KEY (AUTHOR_USERNAME, PUBLICATION_DATETIME) REFERENCES PUBLICATION(AUTHOR_USERNAME, PUBLICATION_DATETIME) ON UPDATE CASCADE,
    PRIMARY KEY(VIEWER_USERNAME, AUTHOR_USERNAME,PUBLICATION_DATETIME)
);

INSERT INTO EXERCISE VALUES 
('Жим лёжа','Выберите скамью для жима лежа, которая соответствует вашему росту и длине рук.
Установите штангу на стойках на высоте, которая позволяет вам легко снимать и класть ее на грудь.
Лягте на скамью так, чтобы ваши ступни были плотно прижаты к полу, а голова и шея поддерживались.
Возьмитесь за штангу хватом чуть шире плеч, ладони направлены вперед. Медленно опустите штангу к груди, держа локти близко к телу.
Опускайте штангу до тех пор, пока она не коснется вашей груди. Мощно выжмите штангу вверх, пока ваши руки не будут полностью разогнуты.
Сосредоточьтесь на использовании мышц груди и трицепсов.
Держите спину прямой и ягодицы прижатыми к скамье.','Абсолютный мировой рекорд по жиму лёжа без экипировки — 355 кг (21 февраля 2021), принадлежит Джулиусу Мэддоксу (Julius Maddox).','207,5кг	Эйприл Мэтис 12.03.2016	SPF	США');

INSERT INTO STANDARDS VALUES
('Жим лёжа','нетренированный',NULL,NULL,'муж',0.5),
('Жим лёжа','начинающий',NULL,NULL,'муж',0.75),
('Жим лёжа','тренированый',NULL,NULL,'муж',1.25),
('Жим лёжа','продвинутый',NULL,NULL,'муж',1.75),
('Жим лёжа','элита',NULL,NULL,'муж',2);

INSERT INTO ATHLETE VALUES
('MAGA2020','SAS123123','DONALD TRUMP','муж',75.6,181,22,'VK.COM');

INSERT INTO COACH VALUES
('MAGA2024','SAS123123','DONALD RUMP','муж',95.6,181,22,'VK.COM','Чемпион KFC');

INSERT INTO ATHLETE_RESULT VALUES
('MAGA2020', 'Жим лёжа', '2024-04-05 11:05:00', 75, 7, 90);

INSERT INTO COACH_RESULT VALUES
('MAGA2024', 'Жим лёжа', '2024-04-05 11:05:00', 75, 7, 90);

INSERT INTO PUBLICATION VALUES
('MAGA2024','2024-04-05 11:05:00','Не окруляйте спину во время становой тяги!');

INSERT INTO ATHLETE_RATING VALUES
('MAGA2020', 'MAGA2024', '2024-04-05 11:05:00', 4, 'Ок, не буду');

INSERT INTO COACH_RATING VALUES
('MAGA2024', 'MAGA2024', '2024-04-05 11:05:00', 4, 'Ок, не буду');
